# Site settings
title: Exploring new world
header-img: img/home-bg.png
email: unmigong@gmail.com
copyright_name: blessedsoy
description: > # this means to ignore newlines until "baseurl:"
  info related to coding
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  blessedsoy
learn_profile: blessedsoy
email_username: unmigong@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
